version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_sae
    environment:
      POSTGRES_DB: but3
      POSTGRES_USER: gregoirelaunaybecueetu
      POSTGRES_PASSWORD: moi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data_sae

volumes:
  postgres_data: